### ISSUE TITLE
Can not proxy my ipv6 connection 

### ISSUE THREAD

**Issue by mzh741** [luoqeng/OpenWrt-on-VMware#2]
The router on virtual machine was set default to use ipv4 protocol. In my situation, I haven't enable dhcp or dhcpv6 server, and the proxy on ipv4 was work fine. Hope you can show me the solution to use the proxy in ipv6 protocol, such as some settings, thanks.

**Comment by luoqeng** [comment]
I suggest you seek help from cokebar@cokebar.info, I just configured it according to the[ blog post](https://cokebar.info/archives/664).
